#******************************************************************************
#
# Custom memory map for Apollo510 for 32K ITCM / 128K DTCM (minimum config.)
#
# The Coremark example for Apollo510 configures memory as:
#   ITCM to 32KB:  0x00000000 - 0x00007FFF
#   DTCM to 128KB: 0x20002000 - 0x20021FFF
#   SSRAM none. So allocate a small amount of DTCM as SSRAM.
#
# Resulting DTCM memory map:
# TCM:   0x20002000 - 0x2001FFFF  (120 KB)
#        8KB shared between SSRAM, heap, and stack.
# SSRAM: 0x20001F00 - 0x20001FFF  ( 256 B)
# HEAP:  0x20001E00 - 0x20001EFF  ( 256 B)
# STACK: 0x20000000 - 0x20001DFF  (7680 B)
#
#******************************************************************************

MemorySections:
    MCU_ITCM:
        start:  0x00000000
        end:    0x00007FFF

    MCU_MRAM:
        start:  0x00410000
        end:    0x007FFFFF

    MCU_TCM:
        start:  0x20002000
        end:    0x2001FFFF

    SHARED_SRAM:
        start:  0x20001F00
        end:    0x20001FFF

    STACK:
        start:  0x20000000
        end:    0x20001DFF

    HEAP:
        start:  0x20001E00
        end:    0x20001EFF


